Repository Undertone0809/promptulate, pull requests merged in 2023-12, with the labels that each got.

#215 feat: add chat tool
  .gitignore
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  README_zh.md
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/get_started/quick_start.md
  docs/images/coverage.svg
  docs/images/logo_transparent.png
  docs/index.html
  docs/modules/agent.md
  docs/modules/chat_usage.ipynb
  docs/modules/chat_usage.md
  docs/modules/client.md
  docs/modules/tools.md
  docs/other/contribution.md
  example/agent/webagent_usage.py
  example/llm/ernie_usage.py
  example/llm/llm_concurrency.py
  example/llm/openai_usage.py
  poetry.lock
  promptulate/__init__.py
  promptulate/agents/web_agent/agent.py
  promptulate/chat.py
  promptulate/client/chat.py
  promptulate/client/pne.py
  promptulate/config.py
  promptulate/error.py
  promptulate/frameworks/conversation/conversation.py
  promptulate/llms/erniebot/erniebot.py
  promptulate/llms/openai/openai.py
  promptulate/memory/buffer.py
  promptulate/memory/file.py
  promptulate/output_formatter/formatter.py
  promptulate/tools/iot_swith_mqtt/tools.py
  promptulate/tools/paper/tools.py
  promptulate/tools/semantic_scholar/api_wrapper.py
  promptulate/utils/__init__.py
  promptulate/utils/core_utils.py
  promptulate/utils/logger.py
  pyproject.toml
  requirements.txt
  setup.py
  tests/test_chat.py
  tests/tools/test_python_repl_tools.py
  tests/tools/test_semantic_scholar_tools.py
  tests/tools/test_sleep_tools.py
Labels: size:XXL

#216 build: using poetry to publish pkg
  .github/workflows/python-publish.yml
Labels: size:M

#218 docs: update docs
  README.md
  README_zh.md
  docs/README.md
  docs/index.html
  pyproject.toml
  setup.py
Labels: documentation, build, size:M

#219 pref: add additional_kwarg of openai
  Makefile
  docs/_sidebar.md
  docs/index.html
  docs/modules/llm/openai.md
  docs/modules/schema.md
  docs/uses_cases/chat_usage.ipynb
  docs/uses_cases/chat_usage.md
  docs/uses_cases/intro.md
  example/llm/custom_conversation.py
  promptulate/llms/erniebot/erniebot.py
  promptulate/llms/openai/openai.py
  pyproject.toml
Labels: documentation, enhancement, size:M

#238 pref: change openai max token length
  promptulate/llms/openai/openai.py
Labels: enhancement, size:XS

#239 fix: change openai max token length
  promptulate/llms/openai/openai.py
Labels: bug, size:XS

#240 pref: add openai parameters
  promptulate/llms/openai/openai.py
Labels: enhancement, size:M

#247 add json schema formatter and pne logger filter
  docs/uses_cases/chat_usage.ipynb
  docs/uses_cases/chat_usage.md
  promptulate/__init__.py
  promptulate/chat.py
  promptulate/output_formatter/formatter.py
  promptulate/output_formatter/prompt.py
  promptulate/utils/logger.py
  tests/test_chat.py
Labels: documentation, enhancement, size:L

#248 fix: error in get litellm response
  promptulate/chat.py
Labels: size:XS

#251 V1.11.0/add template jinja2
  Makefile
  README.md
  README_zh.md
  docs/README.md
  docs/modules/other/string_template.md
  promptulate/client/pne.py
  promptulate/output_formatter/formatter.py
  promptulate/utils/string_template.py
  tests/output_formatter/test_formatter.py
  tests/test_import.py
  tests/utils/test_string_template.py
Labels: dependencies, size:L

#268 fix agent thought bug and update the iot tool prompt
  docs/images/coverage.svg
  promptulate/agents/tool_agent/agent.py
  promptulate/tools/iot_swith_mqtt/prompt.py
Labels: size:S

#269 Revert "fix agent thought bug and update the iot tool prompt"
  docs/images/coverage.svg
  promptulate/agents/tool_agent/agent.py
  promptulate/tools/iot_swith_mqtt/prompt.py
Labels: size:S

#267 feat: support pydantic v2
  promptulate/pydantic_v1/__init__.py
  promptulate/pydantic_v1/dataclasses.py
  promptulate/pydantic_v1/main.py
Labels: enhancement, size:M

#278 pref: optimize calculator, mock for llm and tool
  .github/release-drafter.yml
  Makefile
  README.md
  README_zh.md
  docs/README.md
  docs/modules/tools.md
  example/agent/tool_agent_usage.py
  poetry.lock
  promptulate/tools/math/tools.py
  promptulate/tools/shell/tools.py
  pyproject.toml
  tests/hook/test_llm.py
  tests/hook/test_tool_hook.py
  tests/llms/test_openai.py
  tests/tools/test_calculator.py
  tests/tools/test_duckduckgo_tools.py
  tests/tools/test_human_feedback_tool.py
  tests/tools/test_shell_tool.py
  tests/tools/test_shell_tools.py
  tests/tools/test_sleep_tool.py
Labels: documentation, enhancement, size:L

#270 fix agent thought bug and update the iot tool and the agent prompt
  docs/images/coverage.svg
  example/agent/iot_agent_usage.py
  promptulate/agents/tool_agent/agent.py
  promptulate/agents/tool_agent/prompt.py
  promptulate/tools/iot_swith_mqtt/prompt.py
  tests/hook/test_agent.py
Labels: size:M

#285 pref: optimize calculator
  promptulate/tools/math/prompt.py
  promptulate/tools/math/tools.py
Labels: size:M

#286 pref: optimize logger
  promptulate/utils/logger.py
Labels: size:S
