Repository Undertone0809/promptulate, pull requests merged in 2024-01, with the labels that each got.

#308 feat: add tool schema
  Makefile
  README_zh.md
  docs/README.md
  docs/_sidebar.md
  docs/modules/agent.md
  docs/modules/agents/assistant_agent_usage.ipynb
  docs/modules/tools/custom_tool_usage.md
  docs/modules/tools/index.md
  docs/uses_cases/chat_usage.md
  example/agent/tool_agent_usage.py
  example/tools/custom_tool_usage.ipynb
  poetry.lock
  promptulate/__init__.py
  promptulate/agents/__init__.py
  promptulate/agents/base.py
  promptulate/agents/tool_agent/agent.py
  promptulate/agents/tool_agent/prompt.py
  promptulate/beta/__init__.py
  promptulate/error.py
  promptulate/llms/base.py
  promptulate/llms/openai/openai.py
  promptulate/output_formatter/formatter.py
  promptulate/tools/__init__.py
  promptulate/tools/arxiv/tools.py
  promptulate/tools/base.py
  promptulate/tools/duckduckgo/api_wrapper.py
  promptulate/tools/duckduckgo/tools.py
  promptulate/tools/manager.py
  promptulate/utils/core_utils.py
  promptulate/utils/logger.py
  pyproject.toml
  requirements.txt
  tests/test_import.py
  tests/tools/test_tool.py
Labels: documentation, enhancement, dependencies, build, size:XXL, lgtm

#316 docs: add custom LLM docs
  Makefile
  docs/README.md
  docs/_sidebar.md
  docs/modules/llm/custom_llm.md
  docs/modules/llm/llm.md
  docs/modules/tools/custom_tool_usage.md
  docs/other/knowledge.md
  docs/use_cases/chat_usage.md
  docs/use_cases/intro.md
  example/chat_usage.ipynb
  example/llm/custom_llm.ipynb
  promptulate/llms/base.py
  promptulate/schema.py
  pyproject.toml
  tests/test_chat.py
Labels: documentation, enhancement

#317 arxiv's Chinese prompt was changed to English
  promptulate/tools/arxiv/tools.py
Labels: size:S

#321 fix some bugs and add baseurl to openai
  docs/modules/llm/custom_llm.md
  docs/modules/llm/erniebot.md
  docs/modules/llm/openai.md
  example/llm/openai_usage.py
  promptulate/llms/erniebot/erniebot.py
  promptulate/llms/openai/openai.py
Labels: size:M, lgtm

#327 add qianfan platform support and fix some bugs
  docs/images/qianfan_model.png
  docs/modules/llm/erniebot.md
  example/agent/iot_agent_usage.py
  example/llm/ernie_usage.py
  example/llm/qianfan_usage.py
  promptulate/agents/tool_agent/prompt.py
  promptulate/config.py
  promptulate/llms/__init__.py
  promptulate/llms/base.py
  promptulate/llms/erniebot/erniebot.py
  promptulate/llms/qianfan/__init__.py
  promptulate/llms/qianfan/platform.py
  promptulate/schema.py
  promptulate/tools/__init__.py
  promptulate/tools/sleep/__init__.py
  promptulate/tools/sleep/tool.py
  tests/test_import.py
  tests/tools/test_sleep_tool.py
Labels: size:L, lgtm

#328 build: update poetry.lock
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: size:L

#334 feat: add beta ToolAgent
  docs/use_cases/chat_usage.md
  poetry.lock
  promptulate/agents/assistant_agent/__init__.py
  promptulate/beta/agents/__init__.py
  promptulate/beta/agents/tool_agent/__init__.py
  promptulate/beta/agents/tool_agent/agent.py
  promptulate/beta/agents/tool_agent/notebook.ipynb
  promptulate/tools/__init__.py
  promptulate/tools/duckduckgo/__init__.py
  promptulate/tools/duckduckgo/tools.py
  promptulate/tools/math/__init__.py
  promptulate/tools/math/tools.py
  pyproject.toml
  requirements.txt
Labels: enhancement, size:L

#340 ci: add mac and windows test
  .github/workflows/check.yml
  Makefile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: build, size:L

#341 pref: optimize web-agent
  promptulate/agents/web_agent/agent.py
  pyproject.toml
Labels: bug, enhancement, size:M

#343 docs: update contribution.md
  README_zh.md
  docs/README.md
  docs/other/contribution.md
Labels: size:M

#342 feat: add zhipu llm support and fix some already know bugs
  docs/modules/schema.md
  example/llm/zhipu_usage.py
  poetry.lock
  promptulate/config.py
  promptulate/llms/__init__.py
  promptulate/llms/qianfan/platform.py
  promptulate/llms/zhipu/__init__.py
  promptulate/llms/zhipu/platform.py
  promptulate/schema.py
  promptulate/tools/duckduckgo/tools.py
  promptulate/tools/iot_swith_mqtt/tools.py
  pyproject.toml
  requirements.txt
Labels: documentation, dependencies, build, size:L, lgtm

#365 Update pyproject.toml
  pyproject.toml
Labels: size:XS

#371 feat:add zhipu docs and Optimize the stream of pne implementation
  docs/modules/llm/llm.md
  docs/modules/llm/zhipu.md
  docs/modules/schema.md
  promptulate/chat.py
Labels: size:L, lgtm

#374 bug:add zhipu doc to navbar
  docs/_sidebar.md
Labels: size:XS

#376 bug:add zhipu doc to navbar
  docs/_sidebar.md
  docs/modules/llm/zhipu.md
Labels: size:XS

#382 Paper prompt translation completed
  promptulate/tools/arxiv/tools.py
  promptulate/tools/paper/tools.py
Labels: size:M

#384 docs: update contribution.md
  docs/_sidebar.md
  docs/other/contribution.md
  docs/other/plan.md
Labels: size:M
