Repository Undertone0809/promptulate, pull requests merged in 2024-03, with the labels that each got.

#498 ci: reduce the fre of dependabot
  .github/dependabot.yml
Labels: size:XS

#503 feat: add wikipedia tool
  promptulate/tools/wikipedia/__init__.py
  promptulate/tools/wikipedia/tools.py
Labels: enhancement

#466 add file_operator tools
  example/tools/file_tool_usage.ipynb
  promptulate/tools/__init__.py
  promptulate/tools/file/__init__.py
  promptulate/tools/file/toolkit.py
  promptulate/tools/file/tools.py
  tests/tools/test_file_tools.py
Labels: size:XL

#502 feat:add llm factory
  Makefile
  example/llm/factory.ipynb
  promptulate/__init__.py
  promptulate/llms/__init__.py
  promptulate/llms/factory.py
  tests/llms/test_factory.py
Labels: size:L

#552 feat: optimize pne chat and add AIChat
  README.md
  README_zh.md
  docs/README.md
  docs/get_started/quick_start.md
  docs/modules/agents/assistant_agent_usage.md
  docs/use_cases/chat_usage.md
  example/agent/assistant_agent_usage.ipynb
  example/chat_usage.ipynb
  example/llm/factory.ipynb
  example/output_formatter/output_formatter_with_llm_usage.py
  promptulate/__init__.py
  promptulate/agents/tool_agent/agent.py
  promptulate/beta/agents/assistant_agent/agent.py
  promptulate/beta/agents/assistant_agent/prompt.py
  promptulate/beta/agents/assistant_agent/schema.py
  promptulate/chat.py
  promptulate/hook/base.py
  promptulate/llms/base.py
  promptulate/llms/erniebot/erniebot.py
  promptulate/llms/qianfan/platform.py
  promptulate/output_formatter/formatter.py
  promptulate/pydantic_v1/__init__.py
  promptulate/schema.py
  promptulate/tools/manager.py
  promptulate/uacp/agent.py
  promptulate/uacp/db.py
  pyproject.toml
  tests/output_formatter/test_formatter.py
  tests/test_chat.py
Labels: documentation, enhancement
